version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    # parallelism: 1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/repo

  get_dependencies:
    docker:
      - image: circleci/node:7.10
    # parallelism: 1
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
  test:
    docker:
      - image: circleci/node:7.10
    # parallelism: 1
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test


  build:
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          paths:
            - build
          key: v1-build-{{ checksum ".circle-sha" }}
  deploy:
    docker:
      - image: circleci/node:7.10
    # parallelism: 1
    working_directory: ~/repo
    steps:
      # beware, this script does not seem to work (permission issue on unpacking heroku)
      # It might anyway be unnecessary, because "git push heroku master" already triggers
      # anything we need on heroku
      - run: bash .circleci/setup-heroku.sh
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build
              mkdir to_push
              cp package.json server.js to_push
              cp -R build to_push
              git config --global user.email "ckpinguin@circleci.com"
              git config --global user.name "Chrigi"
              git add to_push
              git commit -m "deploy"
              git push heroku `git subtree split --prefix to_push master`:master --force
              # git subtree push --prefix to_push heroku master
              # heroku run python manage.py deploy
              # heroku restart
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - get_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
            - get_dependencies
      - deploy:
          requires:
            - checkout_code
            - get_dependencies
            - test